# Generated by Django 4.1.6 on 2023-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.SmallIntegerField(default=12, verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класове',
            },
        ),
    ]
