# Generated by Django 4.1.7 on 2023-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_offer_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзив', 'verbose_name_plural': 'Отзиви'},
        ),
        migrations.AddField(
            model_name='offer',
            name='picture',
            field=models.ImageField(blank=True, help_text='Снимка на предлаганите учебници', upload_to='subject_pics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='Съдържание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(default='', max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', help_text='Име на офертата', max_length=100, verbose_name='Име'),
        ),
    ]
