# Generated by Django 4.1.7 on 2023-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_options_offer_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Член на екипа',
                'verbose_name_plural': 'Членове на екипа',
            },
        ),
    ]
